<?php
/** @var \Magestore\Storepickup\Block\Wrapper $block */
?>
<script type="text/javascript">
    var icon_src_loading_wait = '<?php echo $block->getViewFileUrl("Magestore_Storepickup::images/opc-ajax-loader.gif") ?>';
    var time_ajax_loading_wait = '<span class="time-ajax-loading-wait" style="position: relative;">'+ '<img  src="'+ icon_src_loading_wait + '" class="ajax-loading-image"> '+'<?php echo __("Loading") ?>... </span>';
    var date_ajax_loading_wait = '<span class="date-ajax-loading-wait" style="position: relative;">'+ '<img  src="'+ icon_src_loading_wait + '" class="ajax-loading-image"> '+'<?php echo __("Loading") ?>... </span>';
    var save_ajax_loading_wait = '<span class="save-ajax-loading-wait" style="position: relative;display:none;">'+ '<img  src="'+ icon_src_loading_wait + '" class="ajax-loading-image"> '+'<?php echo __("Saving") ?>... </span>';
    var select_store_by_map ='<div id="select_store_by_map" ><?php echo __("Select store by map") ?></div>';
    var storepickup_date_box = '<div id="shipping_date_div" class="storepickup-box col-sm-6 col-xs-12"> Please select Pickup Date/Time to go next step!<br/>'
        + '<label class="required" for="shipping_date"><?php echo __("Pickup Date :") ?> </label>'
        + date_ajax_loading_wait
        + '<input name="shipping_date" style="display:none;" type="text" id="shipping_date" value="" class="input-text required-entry form-control" readonly>'
        + '</div>' +'<br />';
    var storepickup_time_box = '<div id="shipping_time_div" class="storepickup-box col-sm-6 col-xs-12">'
        + '<label class="required" for="shipping_time"><?php echo __("Pickup Time :") ?>  </label>'
        + time_ajax_loading_wait
        + '<select style="display:none;" id="shipping_time" name="shipping_time" class="validate-select"></select>'
        + '</div>'
        +save_ajax_loading_wait;
    var defaultStore= '<?php echo $block->getSystemConfig()->getDefaultStore() ?>';
    var isDisplayPickuptime= '<?php echo $block->getSystemConfig()->isDisplayPickuptime() ?>';
    var storePikcuplatitude="";
    var storePikcuplongitude="";

    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'Magestore_Storepickup/js/checkout/storepickupcheckout'
        ],
        function(
            $,
            modal
        ) {

            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Choose store by map',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));
        }
    );
    window.liststoreJson = <?php echo $block->getListStore() ?>;

</script>

<div id="popup-mpdal" class="storepickup-wrapper col-full" style="display: none;">
    <?php echo $block->getChildHtml('storepickupCheckout.gmapstore') ?>
</div>